### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by daetal-us** [Xunnamius/babel-plugin-explicit-exports-references#1]
Aloha! Thank you for crafting this plugin. Extremely helpful. I was just curious if you had a particular license file in mind/plan to add to repo?

**Comment by Xunnamius** [comment]
@daetal-us Glad you found it useful! The license info should be available at the [root of the repo](https://github.com/Xunnamius/babel-plugin-explicit-exports-references/blob/main/LICENSE). tl;dr it's public domain :)

**Comment by daetal-us** [comment]
Whoops ;)
